---
##############################################################
#
# Site domain
#
# domain = domain to be used for the site
#
# Typically this is defined in the relevant group_vars for the
# inventory that is being deployed
##############################################################
# domain: CHANGEME

##############################################################
#
# Project specific variables
#
# projects.wordpress.path = path on server for the project
# projects.wordpress.repo = repository to fetch from
##############################################################
projects:
  wordpress:
    path: "/srv/www/public"
    repo: "git@github.com:moderntribe/CHANGEME.git"

##############################################################
# project_repo_version = default branch to fetch
##############################################################
project_repo_version: 'HEAD'

##############################################################
# keep_releases = number of release checkouts to retain
##############################################################
keep_releases: 3

##############################################################
#
# Cron
#
# cron_jobs_enabled = setup cron jobs
# cron_jobs = Array of cron jobs
#
# See roles/cron/tasks/main.yml for variables to use in
# cron_jobs array items
##############################################################
cron_jobs_enabled: false
# cron_jobs: []

##############################################################
#
# Datadog
#
# datadog_install = install datadog on this server
# datadog_api_key = API key for datadog
# datadog_config  = config settings for datadog
# datadog_checks  = types of checks datadog should do
#
# Typically these values won't be changed in all/common.yml
# but instead added/changed in the relevant
# inventory/common.yml
##############################################################
datadog_install: false
# datadog_api_key: "CHANGEME"

# datadog_config:
#   hostname: "{{ inventory_hostname }}"
#   tags: 'nginx, php-fpm, production'
#   apm_enabled: no

# datadog_checks:
#   process:
#     init_config:
#     instances:
#       - name: nginx
#         search_string: [ 'nginx' ]
#       - name: php-fpm

##############################################################
#
# Elasticsearch
#
# elasticsearch_enabled = setup elasticsearch (can be external or internally installed service)
# elasticsearch_install = install Elasticsearch on this server
# elasticsearch_plugins = Elasticsearch plugins to use
# elasticsearch_major_version = Version for Elasticsearch
# elasticsearch_endpoint = ES endpoint to use with this installation
#
# Typically these values won't be changed in all/common.yml
# but instead added/changed in the relevant
# inventory/common.yml
##############################################################
elasticsearch_enabled: false
elasticsearch_install: false
# elasticsearch_major_version: "5.x"
# elasticsearch_plugins: []
# elasticsearch_endpoint: http://localhost:9200

##############################################################
#
# Kibana
#
# kibana_install = install Kibana on this server
# kibana_version = Kibana version
# kibana_user = Kibana user
#
# Vars in vault:
# kibana_password = kibana password
#
# Typically these values won't be changed in all/common.yml
# but instead added/changed in the relevant
# inventory/common.yml
##############################################################
kibana_install: false
# kibana_version: "5.2.2"
# kibana_user: pue

##############################################################
#
# Mailhog
#
# mailhog_install  = install mailhog on this server
# mail_admin       = admin email address
# mail_user        = mailhog username
# mail_password    = mailhog password
# mail_hostname    = mailhog hostname
# mail_smtp_server = mail server
#
# Typically these values won't be changed in all/common.yml
# but instead added/changed in the relevant
# inventory/common.yml
##############################################################
mailhog_install: false
# mail_admin: "partners@tri.be"
# mail_user: "{{ smtp_username }}"
# mail_password: "{{ smtp_password }}"
# mail_hostname: "tri.be"
# mail_smtp_server: "CHANGEME"

##############################################################
#
# Memcached
#
# memcached_enabled       = setup memcached (can be external or internally installed service)
# memcached_install      = indicates whether the memcached install should happen on the server being configured
#
# These are the other vars. The commented out values are the defaults
# memcached_port          = port for memcached
# memcached_listen_ip     = ip address memcached will listen on
# memcached_user          = user under which memcached daemon will run
# memcached_memory_limit  = max amount of RAM (in MB)
# memcached_connections   = max number of simultaneous connections
# memcached_log_file      = location of log file
# memcached_log_verbosity = -v is logging and -vv is debug logging
##############################################################
memcached_enabled: false
# memcached_install: true
# memcached_port: 11211
# memcached_listen_ip: 127.0.0.1
# memcached_user: memcache
# memcached_memory_limit: 64
# memcached_connections: 1024
# memcached_log_file: /var/log/memcached.log
# memcached_log_verbosity: ""

##############################################################
#
# Newrelic
#
# newrelic_install = install newrelic on this server
# newrelic_appname = name as it should appear in Newrelic
#
# Vars in vault:
# newrelic_license = Newrelic License
#
# Typically these values won't be changed in all/common.yml
# but instead added/changed in the relevant
# inventory/common.yml
##############################################################
newrelic_install: false
# newrelic_appname: "CHANGEME"

##############################################################
#
# Redis
#
# redis_install = install redis on this server
# redis_host = host for redis
#
# Typically these values won't be changed in all/common.yml
# but instead added/changed in the relevant
# inventory/common.yml
##############################################################
redis_install: false
# redis_host: localhost

##############################################################
# web_user = user for www execution
##############################################################
web_user: www-data

##############################################################
# ssl_self_signed = use self signed cert for SSL?
##############################################################
ssl_self_signed: no

##############################################################
# common_apt_packages = apt-get packages to install
##############################################################
common_apt_packages:
  - acl
  - build-essential
  - curl
  - git
  - jq
  - lnav
  - nodejs
  - npm
  - python-pip
  - unzip
  - yarn
  - zip

##############################################################
# yarn_debian_repo_url = apt-get repo that has the yarn pkg
# yarn_debian_repo_gpg_key_url = key for accessing the repo
##############################################################
yarn_debian_repo_url: "https://dl.yarnpkg.com/debian/ stable main"
yarn_debian_repo_gpg_key_url: "https://dl.yarnpkg.com/debian/pubkey.gpg"

##############################################################
# This setting is to add any extra code to local-config.php
# that's not covered in the template. Be mindful of what you
# add here, as there is no validation. Also keep in mind that
# it requires the pipe and indentation to be respected.
# Furthermore, if these should be api keys or other sensitive
# information, this config SHOULD BE VAULTED.
# local_config_extras: |
#   define( 'SOMETHING_API_KEY', 'herp' );
#   define( 'VERY_SECRET_VALUE', 'derp' );
##############################################################
# local_config_extras: |
