---
##############################################################
# Vars in vault:
# mysql_root_username = master user for database
# mysql_root_password = password for master user
##############################################################

##############################################################
# mysql_databases.name = name of WP database
##############################################################
mysql_databases:
  - name: "{{ wp_site_db_name }}"

##############################################################
# mysql_users.name = WP db username
# mysql_users.password = WP db password
# mysql_users.priv = privileges for the WP db user
##############################################################
mysql_users:
  - name: "{{ wp_site_db_user }}" # This should NOT be a shared user because it'd lock them out of doing anything else beyond {{wp_site_db_name}}
    password: "{{ wp_site_db_password }}"
    priv: "{{ wp_site_db_name }}.*:ALL"

##############################################################
# mysql_packages = Packages to install with apt-get
#
# Typically this is only needed for non-rds database setups
# meaning development
##############################################################
# mysql_packages:
#   - mariadb-client
#   - mariadb-server
#   - python-mysqldb
