---
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_enable_webserver: true
php_webserver_daemon: nginx
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_protocol: "" # used for nginx config, 'unix://' if using socket, otherwise blank
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 8
php_fpm_pm_min_spare_servers: 8
php_fpm_pm_max_spare_servers: 8

php_packages:
  - php7.1-common
  - php7.1-cli
  - php7.1-dev
  - php7.1-fpm
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php7.1-opcache
  - php7.1-xml
  - php7.1-mbstring
  - php-apcu
  - php7.1-bcmath
  - php7.1-zip
  - php7.1-mysql

# PHP-FPM 7.1
php_conf: "/etc/php/7.1"
php_conf_paths:
  - "{{ php_conf }}/fpm"
  - "{{ php_conf }}/apache2"
  - "{{ php_conf }}/cli"

php_extension_conf_paths:
  - "{{ php_conf }}/fpm/conf.d"
  - "{{ php_conf }}/apache2/conf.d"
  - "{{ php_conf }}/cli/conf.d"

php_fpm_daemon: php7.1-fpm
php_fpm_conf_path: "{{ php_conf }}/fpm"
php_fpm_pool_conf_path: "{{ php_fpm_conf_path }}/pool.d/www.conf"

php_fpm_pool_user: www-data
php_fpm_pool_group: www-data