---
- src: geerlingguy.php
- src: geerlingguy.composer
- src: geerlingguy.mailhog
- src: geerlingguy.mysql
- src: geerlingguy.redis
- src: Datadog.datadog
- name: tribe
  src: ssh://git@github.com/moderntribe/tribe-ansible-roles.git
  scm: git
  path: ./roles